### ISSUE TITLE
When trying to compile with a capacitor 3 project I get the following error

### ISSUE THREAD

**Issue by pankajdreamsoft** [veloce/capacitor-sound-effect#5]
capacitor-sound-effect Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0

If i am trying to downgrade iOS target version 11.0 for capacitor-sound-effect then it's not allowing to capacitor because capacitor 3 allow minimum 12.0.

**Comment by veloce** [comment]
Should be ok now.
