### ISSUE TITLE
Update to capacitor 4.0

### ISSUE THREAD

**Issue by ghost** [veloce/capacitor-sound-effect#8]
I tested it out here on android (https://github.com/jrobeson/capacitor-sound-effect/commit/bfed98fcb19289481a8025b1639d3666f069adff), but i don't have an iphone to test with.

I also notice that upgrades will change the output of the doc generation, so I didn't submit a PR. I could still do so if you wanted me to though.

**Comment by Hambat** [comment]
Accept?
